### ISSUE TITLE
faceting tooltip on products page shows up in the wrong place

### ISSUE THREAD

**Issue by cmlizama** [BestBuyAPIs/bby-query-builder#100]
it sits above the entire div rather than the tooltip icon itself

**Comment by cmlizama** [comment]
should be good now
![screen shot 2015-02-23 at 11 27 23 am](https://cloud.githubusercontent.com/assets/5415869/6332964/faa6ec22-bb4e-11e4-9650-cd38081062ac.png)

**Comment by juliemuraski** [comment]
reproduced in prod
