### ISSUE TITLE
add category path and name to the attributes dropdown on products tab

### ISSUE THREAD

**Issue by cmlizama** [BestBuyAPIs/bby-query-builder#112]

**Comment by cmlizama** [comment]
![screen shot 2015-04-01 at 10 46 12 am](https://cloud.githubusercontent.com/assets/5415869/6944994/56196fe2-d85c-11e4-8d4e-be7a840519bc.png)

**Comment by juliemuraski** [comment]
Can we add an * at the end of the Category Path Name

like 

https://api.remix.bestbuy.com/v1/products(categoryPath.name=mot*)?apiKey=rbda762vjychtktzbj8kdcn4&sort=sku.asc&show=sku,categoryPath.name&callback=JSON_CALLBACK&format=json

**Comment by juliemuraski** [comment]
Looks great
