### ISSUE TITLE
Need consistent representation of "format=json" across Products, Stores and Categories tabs

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-builder#117]
Recommend adding it to anatomy and the complete URL in a consistent place.

Products
![image](https://cloud.githubusercontent.com/assets/6863908/6597497/173e2f84-c7cb-11e4-8e02-f53b95cdf48e.png)

Stores
![image](https://cloud.githubusercontent.com/assets/6863908/6597512/361f6062-c7cb-11e4-8df0-58a77d0cadbe.png)

Categories
![image](https://cloud.githubusercontent.com/assets/6863908/6597528/5a70148e-c7cb-11e4-9ce0-4d7408d036ab.png)

**Comment by cmlizama** [comment]
addressed with 08afe437b66cdce370ed15698d509d425f6df10b

**Comment by juliemuraski** [comment]
Verified locally
