### ISSUE TITLE
Cannot search by Category Id after searching by Category Name

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-builder#121]
![image](https://cloud.githubusercontent.com/assets/6863908/6600380/414c9b1e-c7dd-11e4-8289-10d264763ce5.png)

**Comment by cmlizama** [comment]
this will most likely have been fixed with 098ec250955f6378b5185dca6b8bc4a78a64accc as well

**Comment by juliemuraski** [comment]
Works locally
