### ISSUE TITLE
Categories giving mixed content error; results not returnable for any Category option

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-builder#125]
![image](https://cloud.githubusercontent.com/assets/6863908/6709541/2dc98712-cd48-11e4-8d7e-acc668aa1ff4.png)

**Comment by cmlizama** [comment]
fixed with 26b51712a367f0d0a009d07eed44eea633e32ed4

**Comment by juliemuraski** [comment]
Tested
