### ISSUE TITLE
Add option to "Build Your Response" to show all attributes for a product (show=all)

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-builder#31]

**Comment by cmlizama** [comment]
In effect, this happens if you leave the Show Options field blank (it shows all attributes of the product.) Perhaps we could have copy to illustrate that this is happening?

**Comment by juliemuraski** [comment]
Actually show=all shows you additional attributes then if you had specified a show option. Either way I think this is outside the scope of the QueryBuilder and am closing this enhancement.
