### ISSUE TITLE
'sort by' should have the attributes picked up from the list of attributes selected to build the rsponse

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-builder#69]
Ex: if the user selects show=sku,saleprice,type&sort by=bestSellingRank , it may not be useful.

**Comment by juliemuraski** [comment]
Passed in production

![image](https://cloud.githubusercontent.com/assets/6863908/6337206/e8e8764e-bb6d-11e4-87d9-726c0885bfc0.png)
