### ISSUE TITLE
when no value is selected for a facet attribute, result set should default to 10

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-builder#71]
ex: facets:color and number is left blank,
the generated query doesn't have a facet

https://api.remix.bestbuy.com/v1/products((bestSellingRank=))?apiKey=b6qgvh88dwuc26hssgp2cb4a&callback=JSON_CALLBACK&sort=bestSellingRank.asc&show=sku,name,salePrice&pageSize=10&page=1&format=json

expected:

https://api.remix.bestbuy.com/v1/products((bestSellingRank=))?apiKey=b6qgvh88dwuc26hssgp2cb4a&callback=JSON_CALLBACK&sort=bestSellingRank.asc&show=sku,name,salePrice&pageSize=10&page=1&format=json&facet=color,10

**Comment by juliemuraski** [comment]
Talked with Chris and Remix should already default to ten so we are going to remove requiring a value to be entered and as long as an attribute is selected add it to the query.

**Comment by juliemuraski** [comment]
Passed in production

![image](https://cloud.githubusercontent.com/assets/6863908/6337163/a3b4fdfe-bb6d-11e4-94e9-d89353219a86.png)
