### ISSUE TITLE
Line up Faceting and Sorting 

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-builder#97]
![image](https://cloud.githubusercontent.com/assets/6863908/6261751/4b345276-b7ba-11e4-87b1-90224122a17f.png)

**Comment by jkap** [comment]
Lining up the Facets and Sort labels would make the actual dropdowns be misaligned, which I think is worse. Additionally, the labels currently are aligned, but they're both right justified.

I don't think this should be changed.

**Comment by cmlizama** [comment]
![labels](https://cloud.githubusercontent.com/assets/5415869/6332916/b068e854-bb4e-11e4-84b2-c2b637ff1272.png)

**Comment by juliemuraski** [comment]
Reproduced in prod
